# Schema for the configuration files of the Viewfield module.

field.storage_settings.viewfield:
  type: mapping
  label: 'Viewfield storage settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'

field.field_settings.viewfield:
  type: mapping
  label: 'Viewfield settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.[%parent.handler]
      label: 'Viewfield selection plugin settings'
    force_default:
      type: boolean
      label: 'Always use default value'
    allowed_views:
      type: sequence
      label: 'Allowed views'
      sequence:
        - type: string
          label: 'Allowed view'
    allowed_display_types:
      type: sequence
      label: 'Allowed display types'
      sequence:
        - type: string
          label: 'Allowed display type'

field.value.viewfield:
  type: field.value.entity_reference
  label: 'Default value'
  mapping:
    target_id:
      type: integer
      label: 'View'
    target_uuid:
      type: string
      label: 'Target UUID'
    display_id:
      type: string
      label: 'Display ID'
    arguments:
      type: string
      label: 'Arguments'

field.widget.settings.viewfield_select:
  type: mapping
  label: 'Viewfield widget settings'

field.formatter.settings.viewfield_default:
  type: mapping
  label: 'Viewfield format settings'
  mapping:
    view_title:
      type: string
      label: 'View title'
    always_build_output:
      type: string
      label: 'Always build output'
    empty_view_title:
      type: string
      label: 'Empty view title'
